### ISSUE TITLE
Fails to build in dockerhub

### ISSUE THREAD

**Issue by yookoala** [Cangjians/pycangjie#36]
Looks like Dockerhub provides no way inject environment variable in the build process. So the `ARG` based docker image `FROM` statement fails:
https://hub.docker.com/r/cangjians/pycangjie/builds/bklokftnqnqe4en7tgnzw6h/

It is, however, possible to build images in Travis then push to dockerhub, see "Pushing a Docker Image to a Registry" in [their documentaiton](https://docs.travis-ci.com/user/docker/):

> ### Pushing a Docker Image to a Registry
> 
> In order to push an image to a registry, one must first authenticate via `docker
> login`.  The email, username, and password used for login should be stored in
> the repository settings environment variables, which may be set up through the
> web or locally via the Travis CLI, e.g.:
> 
> ```bash
> travis env set DOCKER_USERNAME myusername
> travis env set DOCKER_PASSWORD secretsecret
> ```
> 
> Within your `.travis.yml` prior to attempting a `docker push` or perhaps before
> `docker pull` of a private image, e.g.:
> 
> ```bash
> docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
> ```

**Comment by bochecha** [comment]
Oh no, that's my fault! I forgot to add the `hooks/build`, like I did for libcangjie.

**Comment by bochecha** [comment]
As for pushing during the build, that's neat, but it doesn't solve the problem: it means pycangjie images are only ever pushed when we run the CI, not when the underlying libcangjie images change.

So we really need the automatic builds to work, and for that we need the same hook as we have for libcangjie.
